name: text-r
version: 0.1.0
homepage: https://github.com/morloclib/text-r
synopsis: R implementations for text operations
description: R implementations for text operations
category: data
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/text-r
bug-reports: https://github.com/morloclib/text-r
